### PR TITLE
Fix/#266 provide powerfactor mode

### PR DESCRIPTION
**Pull request by boltbeard**

### CODE REVIEW

**Comment by nesnoj** [comment]
Still pending?

**Comment by boltbeard** [comment]
Yes, I would also like to do a few more exhaustive tests. The code works with some test networks I generated. It would be good to have a comparison of the impact before and after.

**Comment by boltbeard** [comment]
Just to check it the pytests run as expected (which they do) I opened a new branch test/power_factor_mode, this can be deleted once this PR is merged

**Comment by gplssm** [comment]
A first scan of this PR brought the following questions

- [ ] Which parts of the code have to be changed when introducing the sign convention for inductive/capacitive reactive power?
  * PyPSA IO
  * Is the sign convention introduced by @boltbeard correct?
  * How does newly introduced sign convention changes the results?

But, first of all, the sign convention be understood entirely!

**Comment by gplssm** [comment]
The sign convention is now clarified and the description provided in the docs is correct!

One question remains: Are loads and generators operated inductive or capacitive?
The document "Erzeugungsanlagen am Niederspannungsnetz – Technische Mindestanforderungen für  Anschluss und Parallelbetrieb von Erzeugungsanlagen am Niederspannungsnetz" (VDE AR-N 4105) just specify the range in which assets must operate (cos(phi) 0.9...0.95 capacitive/inductive) but does not specify the exact set point.

This PR introduces default settings such that
* Generators behave capacitive
* Loads behave inductive

Is this a correct and good assumption? As far as I know, capacitive behaviour of generators leads to a voltage increase.

**Comment by gplssm** [comment]
Closes #266

**Pull request merged**
