### PR TITLE
Features/stats export

### PR DESCRIPTION
**Pull request by boltbeard**
The tasks from #256 was not completely finished, these are still in the works.

> This PR includes the CSV + OEDB grid data exporting functions.

> The CSV export seems to work quite well, the OEDB export requires some more work.

> An exemplary script for exporting ding0 data to OEDB can be found [here](https://gist.github.com/gplssm/cf7462337fa80578bbffb6b5ce59a42b).

### Tasks for both exporters
- [x] Include weather_cell_id
- [x] Add metadata export. For CSV export simply use the [existing JSON-metadata export](https://github.com/openego/ding0/blob/9cc9e2ef5f2dc1ff7053de481cd848487bec8da4/ding0/core/__init__.py#L1764-#L1823)
- [x] Correct the metadata that has to be exported with the two exporters.
- [x] Do not aggregated generators while exporting data from Ding0 #265.
- [x] Complete documentation about this features i.e. #269 (but more)
- [x] Align structure and in particular column names between different exporters/importers #268 

### Tasks only for OEDB export
- [x] Make sure tables can be written to OEDB
- [x] Make sure `run_id` is unique in OEDB (ask Ludwig for help on database stuff)
- [x] Include [export_network()](https://github.com/openego/ding0/blob/43069347dc3f8a0f63b0007ffc351cf17e40d383/ding0/tools/results.py#L1580-#L2139) in [export_data_to_oedb()](https://github.com/openego/ding0/blob/43069347dc3f8a0f63b0007ffc351cf17e40d383/ding0/tools/results.py#L2171-#L2349)
- [x] Add metadata to OEDB tables. This is a simple string which only holds the version of the software (Note, this is other metadata than above! -> Ask Ludwig for help/instructions) #270 

Along with these the issues in #263  need to also be made

### Tasks for versioning data in OEDB
- [x] Use the current versioning setup through `ego_grid_ding0_versioning` for moving the data from `model_draft` to `supply`
- [x] Fill the correct information for the metadata to be filled into the versioned tables in this [spreadsheet](https://docs.google.com/spreadsheets/d/1gSQ_H6zKo640TK705NeWBRRKsJkgKpcwdtk0g9AXX-w/edit?usp=sharing)
- [x] Insert the metadata in the excel sheet into the versioned data, try to automate the generation of the metadata strings.
- [x] Support the review process. Refer to [issue #7 in OpenEnergyPlatform/data-preprocessing](https://github.com/OpenEnergyPlatform/data-preprocessing/issues/7)

### CODE REVIEW

**Comment by nesnoj** [comment]
Any news here?

**Comment by jh-RLI** [comment]
As I try to check all tasks I´m not sure what is about :
- Correct the metadata that has to be exported with the two exporters. (OEDB-metadata? or ding0 metadata?)

**Comment by jh-RLI** [comment]
@gplssm I will review my code and try to clean it up. I could provide a documentation, is there a specific template somewhere?

**Comment by gplssm** [comment]
Regarding your questions
> * Correct the metadata that has to be exported with the two exporters. (OEDB-metadata? or ding0 metadata?)

Means just that the metadata that is provided by both of the exporters should be correct. Can you verify that?

> * Include export_network() in export_data_to_oedb()

You did this! For example, `export_network_tocsv()` uses the output of the function `export_network()`

**Comment by gplssm** [comment]
> @gplssm I will review my code and try to clean it up. I could provide a documentation, is there a specific template somewhere?

There is not really a template, but best-practice. This includes that functions are properly documented, additionally the coded can include some comments for better understanding and there should be some written text that tells new users about how to use the data exporters.
There is already something [documented](https://dingo.readthedocs.io/en/dev/usage_details.html#csv-file-export). It would be perfect if you could 
* complete and correct these tables that describe the resulting data
* Add some text that roughly describes how to use the data exporters

**Comment by mltja** [comment]
Closed due to deprecation through breaking changes in ding0, mentioned in #384

**Pull request closed without merging**
