### PR TITLE
Feature/refactoring

### LINKED ISSUE #307: PyPSA format CSV file export
## Goal

A method `NetworkDing0.to_csv()` that saves Ding0 data to CSV files in an extended PyPSA format, such that data required by eDisGo is included.

## What is expected? Where to start?

At the moment, this can be done partially: MV data without the MV-LV transformers can be exported by (assumes a ding0 network `nd` exists)

```
from ding0.tools.pypsa_io import create_powerflow_problem, export_to_dir

comps, comps_data = list(nd.mv_grid_districts())[0].mv_grid.export_to_pypsa(session)
network, snapshots = create_powerflow_problem(
    pd.DatetimeIndex(freq='H',
                              periods=1,
                              start=datetime(1970, 1, 1, 00, 00, 0)),
    comps)
export_to_dir(network, export_dir='/home/guido/rli-lokal/245_open_BEA/new_ding0_data_format/PyPSA_CSV_tables/')
```

The export into the extended PyPSA format shall meet the following requirements/ has following features

* One grid is exported at once
* Each component has a unique name
* MV and LV data are saved to the same files

## Tasks

- [x] Decide if MV-LV transformers are included in MV or LV part of the exporter
- [x] Add transformers to the set of data that is translated to PyPSA (see [here](https://github.com/openego/ding0/blob/dev/ding0/tools/pypsa_io.py#L63-L81))
- [x] Extend data that is translated to PyPSA (use [this list](https://github.com/openego/ding0/files/3606789/20190909_PyPSA-CSV-for-eDisGo-Import.xlsx) to know about which data it is to be extended)
- [x] Implement translation to PyPSA for LV similarly to [implementation for MV](https://github.com/openego/ding0/blob/dev/ding0/core/network/grids.py#L675-L743)
- [x] Add function `NetworkDing0.to_csv()` that does the whole thing (export of MV and LV data)
- [ ] Remove [this function](https://github.com/openego/ding0/blob/4919579ed7e808ffd66ec3b28ca819a0039b711f/ding0/tools/pypsa_io.py#L40) and close #220
- [x] Tests for newly implemented functions that are related to this issues
- [ ] Add documentation of the data in exported table (what is it, units, ...)
- [ ] List changes in _What's New_
- [x] Circuit Breaker handling: Export or move to new issue
- [ ] Update docstrings

## Extras

Things that are nice, but might blow the issue too much

- [x] remove 1m line connection of components directly connected to transformers (HV-MV and MV-LV) and connect components directly to the busbar
- [ ] Tests for existing methods/functions that compose the data for CSV file export (maybe move this into a separate issue that is to be done afterwards)
- [x] Change handling of aggregated load areas. Introduce transformers and attach loads and generators to LV side of these transformers instead of directly at the substation. This way, the components are connected to a LV bus, which is more plausible.
- [ ] Change in_building generators and loads export. Instead of creating new bus for these components, attach them to the previous in_building-BranchTee and delete lines.

**Note** feel free to edit the description of this issue such that it supports the implementation!

### PR DESCRIPTION
**Pull request by AnyaHe**
Fix #307.

### CODE REVIEW

**Comment by gplssm** [comment]
I have found a bug in the newly introduced function `relocate_circuit_breaker()`.

```
INFO:ding0:=====> Generators connected
Traceback (most recent call last):
  File "utils/retrieve_data.py", line 75, in <module>
    ding0_data = generate_ding0_data(g, settings['csv_data_path'])
  File "utils/retrieve_data.py", line 17, in generate_ding0_data
    nd.run_ding0(session=session,mv_grid_districts_no=[grid_id])
  File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/__init__.py", line 328, in run_ding0
    self.set_circuit_breakers(debug=debug)
  File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/__init__.py", line 1927, in set_circuit_breakers
    grid_district.mv_grid.set_circuit_breakers(debug=debug)
  File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/network/grids.py", line 818, in set_circuit_breakers
    set_circuit_breakers(self, debug=debug)
  File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/grid/mv_grid/tools.py", line 198, in set_circuit_breakers
    relocate_circuit_breaker(circ_breaker, mv_grid, position, ring)
  File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/grid/mv_grid/tools.py", line 94, in relocate_circuit_breaker
    node2 = ring[position + 1]
IndexError: list index out of range
```

It appears when you run ding0 on another grid id than 460, for example 637.

**Comment by gplssm** [comment]
One more... :male_detective: 

For [the visualization ](https://github.com/gplssm/ding0_viz) I filter generators by `v_nom > 0.4` to exclude the generators connected to the LV grid. 

With `v_nom > 0.4` (missing generators in MV)
Bildschirmfoto_2019-10-24_13-37-01

Without `v_nom > 0.4` (no missing generators in MV, but lots of LV generators flying around)
Bildschirmfoto_2019-10-24_13-38-16

`v_nom` is taken from buses where generators are joined to.

**Comment by AnyaHe** [comment]
> 
> 
> One more... 🕵
> 
> For [the visualization ](https://github.com/gplssm/ding0_viz) I filter generators by `v_nom > 0.4` to exclude the generators connected to the LV grid.
> 
> With `v_nom > 0.4` (missing generators in MV)
> Bildschirmfoto_2019-10-24_13-37-01
> 
> Without `v_nom > 0.4` (no missing generators in MV, but lots of LV generators flying around)
> Bildschirmfoto_2019-10-24_13-38-16
> 
> `v_nom` is taken from buses where generators are joined to.

Thanks for pointing that out. What do you mean by generators are missing in MV? Do you expect aggregated generators for LV grid districts or are actual MV generators missing?

**Comment by AnyaHe** [comment]
> 
> 
> I have found a bug in the newly introduced function `relocate_circuit_breaker()`.
> 
> ```
> INFO:ding0:=====> Generators connected
> Traceback (most recent call last):
>   File "utils/retrieve_data.py", line 75, in <module>
>     ding0_data = generate_ding0_data(g, settings['csv_data_path'])
>   File "utils/retrieve_data.py", line 17, in generate_ding0_data
>     nd.run_ding0(session=session,mv_grid_districts_no=[grid_id])
>   File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/__init__.py", line 328, in run_ding0
>     self.set_circuit_breakers(debug=debug)
>   File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/__init__.py", line 1927, in set_circuit_breakers
>     grid_district.mv_grid.set_circuit_breakers(debug=debug)
>   File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/core/network/grids.py", line 818, in set_circuit_breakers
>     set_circuit_breakers(self, debug=debug)
>   File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/grid/mv_grid/tools.py", line 198, in set_circuit_breakers
>     relocate_circuit_breaker(circ_breaker, mv_grid, position, ring)
>   File "/home/guido/rli/git/ding0_viz/src/ding0/ding0/grid/mv_grid/tools.py", line 94, in relocate_circuit_breaker
>     node2 = ring[position + 1]
> IndexError: list index out of range
> ```
> 
> It appears when you run ding0 on another grid id than 460, for example 637.

Thank you for the testing. That probably happens when the station is the last node in the list. I will find a workaround.

**Comment by gplssm** [comment]
> > One more... male_detective
> > For [the visualization ](https://github.com/gplssm/ding0_viz) I filter generators by `v_nom > 0.4` to exclude the generators connected to the LV grid.
> > With `v_nom > 0.4` (missing generators in MV)
> > Bildschirmfoto_2019-10-24_13-37-01
> > Without `v_nom > 0.4` (no missing generators in MV, but lots of LV generators flying around)
> > Bildschirmfoto_2019-10-24_13-38-16
> > `v_nom` is taken from buses where generators are joined to.
> 
> Thanks for pointing that out. What do you mean by generators are missing in MV? Do you expect aggregated generators for LV grid districts or are actual MV generators missing?

When you compare the first with the second picture, between the two transformers (blue points) on the top, you see a difference: in the second picture there are generators (green points) connceted to the lines. In the first these generators aren't there and the lines lead to nowhere. These shouldn't be aggregated generators. Just normal generators connect at MV level. Do you get what I mean?

**Comment by nesnoj** [comment]
Tests fixed and aligned with dev :tada:

**Pull request merged**
